### ISSUE TITLE
您好，這個例子在HSQLDB上測試是OK的

### ISSUE THREAD

**Issue by timloo0710** [blade-samples/blog#2]
App.java 裏修改
		DB.open("org.hsqldb.jdbcDriver", "jdbc:hsqldb:hsql://localhost/blog01", "SA", "", true);

blog.sql 修改

CREATE TABLE t_post (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 2, INCREMENT BY 1) PRIMARY KEY,
  title varchar(50) DEFAULT NULL,
  content CLOB,
  view_count INTEGER DEFAULT 0,
  create_time TIMESTAMP NOT NULL
) ;

在POM.XML裏
加上，

		<dependency>
    <groupId>org.hsqldb</groupId>
    <artifactId>hsqldb</artifactId>
    <version>2.3.4</version>
		</dependency>

然後就可正常運作。

很棒，加油。

**Comment by biezhi** [comment]
👍  nice，这个我还没有试过！
